/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpr.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author atmik shetty
 */
public class GS extends javax.swing.JFrame {

    /**
     * Creates new form GS
     */
    public GS() {
        initComponents();
    }
    
     public GS(String voter1, String pres1, String lr1) {
        initComponents();
        pres_2.setText(pres1);
        voter_3.setText(voter1);
        lr_1.setText(lr1);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ashutosh = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        girish = new javax.swing.JRadioButton();
        gnext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pres_2 = new javax.swing.JLabel();
        voter_3 = new javax.swing.JLabel();
        lr_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("GENERAL SECRETARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 280, 53));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CANDITATE 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 60));

        ashutosh.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ashutosh.setForeground(new java.awt.Color(255, 255, 255));
        ashutosh.setText("ASHUTOSH MISHRA");
        ashutosh.setContentAreaFilled(false);
        ashutosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ashutoshActionPerformed(evt);
            }
        });
        getContentPane().add(ashutosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("CANDITATE 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 60));

        girish.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        girish.setForeground(new java.awt.Color(255, 255, 255));
        girish.setText("GIRISH SURVE");
        girish.setContentAreaFilled(false);
        girish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girishActionPerformed(evt);
            }
        });
        getContentPane().add(girish, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 35));

        gnext.setBackground(new java.awt.Color(51, 0, 51));
        gnext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gnext.setForeground(new java.awt.Color(255, 255, 255));
        gnext.setText("NEXT");
        gnext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gnext.setContentAreaFilled(false);
        gnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnextActionPerformed(evt);
            }
        });
        getContentPane().add(gnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 137, 82));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\atmik shetty\\Pictures\\Screenshots\\background1.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        pres_2.setText("jLabel5");
        getContentPane().add(pres_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        voter_3.setText("jLabel5");
        getContentPane().add(voter_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        lr_1.setText("jLabel5");
        getContentPane().add(lr_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnextActionPerformed
        // TODO add your handling code here:       
                
                
                if(ashutosh.isSelected()){
                String pres2 = pres_2.getText();
                String lr1 = lr_1.getText();
                String voter3 = voter_3.getText();
                String gs1 = ashutosh.getText();
                new RR(voter3, pres2, lr1, gs1).setVisible(true);
                setVisible(false);  
                dispose();
                } 
                 
                else if(girish.isSelected()){
                String pres2 = pres_2.getText();
                String lr1 = lr_1.getText();
                String voter3 = voter_3.getText();
                  String gs1 = girish.getText();
                new RR(voter3, pres2, lr1, gs1).setVisible(true);
                setVisible(false);    
                dispose();
                }
                
                else{
                     JOptionPane.showMessageDialog(null,"select atleast one canditate!!!");
                }
                   
                   
    }//GEN-LAST:event_gnextActionPerformed

    private void ashutoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ashutoshActionPerformed
        // TODO add your handling code here:
                if(ashutosh.isSelected()){
            girish.setSelected(false);
            
        }
    }//GEN-LAST:event_ashutoshActionPerformed

    private void girishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girishActionPerformed
        // TODO add your handling code here:
                if(girish.isSelected()){
            ashutosh.setSelected(false);
           
        }
    }//GEN-LAST:event_girishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ashutosh;
    private javax.swing.JRadioButton girish;
    private javax.swing.JButton gnext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lr_1;
    private javax.swing.JLabel pres_2;
    private javax.swing.JLabel voter_3;
    // End of variables declaration//GEN-END:variables
}
