/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpr.pkg1;

import java.util.regex.*;
import javax.swing.JPasswordField;
import javax.swing.JOptionPane;
import java.sql.*;

import java.awt.Dimension;
import java.util.regex.*;
import javax.swing.JPasswordField;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author atmik shetty
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
    }
    
    Connection connection = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PID_WARN = new javax.swing.JLabel();
        NAME_WARN = new javax.swing.JLabel();
        login_name = new javax.swing.JTextField();
        login_pid = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("STUDENT COUNCIL ELECTIONS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, 40));

        PID_WARN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PID_WARN.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(PID_WARN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, 30));

        NAME_WARN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        NAME_WARN.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(NAME_WARN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 180, 30));

        login_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_nameActionPerformed(evt);
            }
        });
        getContentPane().add(login_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 180, 30));

        login_pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_pidActionPerformed(evt);
            }
        });
        getContentPane().add(login_pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, 30));

        show.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("SHOW PID");
        show.setBorder(null);
        show.setContentAreaFilled(false);
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 130, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\atmik shetty\\Pictures\\Screenshots\\background1.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                

        if(login_name.getText().trim().isEmpty() && login_pid.getText().trim().isEmpty()){
            NAME_WARN.setText("!! Enter Name !!");
            PID_WARN.setText("!! Enter Password !!");
        }
        else if(login_name.getText().trim().isEmpty()){
            NAME_WARN.setText("!! Enter Name !!");
        }
        else if(login_pid.getText().trim().isEmpty()){
            PID_WARN.setText("!! Enter PID !!");
        }
        
        
               
        else{
            String username=login_name.getText();
            String password=login_pid.getText();
        
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/userdata","root","");
            Statement stat = con.createStatement();
            String st = login_name.getText();
            String selectQuery = "SELECT COUNT(*) from voting_details where Voter = '"+st+"'";
            ResultSet rs = stat.executeQuery(selectQuery) ;
            rs.next();
            String Countrow = rs.getString(1);
            if(Countrow.equals("1")){
                JOptionPane.showMessageDialog(null,"! Voting Already Done.!");
                login_name.setText("");
            }
            else{
                 String url="select NAME , PID from login_data where NAME ='"+username+"' and PID ='"+password+"'";
            ResultSet set= stat.executeQuery(url);
            if(set.next()){
                JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL");
                String voter1 = login_name.getText();
                
                
                dispose();
                new President(voter1).setVisible(true);
                setVisible(false);
                
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid Name or Password !");
            }
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
           
        
        }     

                
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void login_pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_pidActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if (show.isSelected()){
            login_pid.setEchoChar((char)0);
        }
        else {
            login_pid.setEchoChar('*');
        }
    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAME_WARN;
    private javax.swing.JLabel PID_WARN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login_name;
    private javax.swing.JPasswordField login_pid;
    private javax.swing.JCheckBox show;
    // End of variables declaration//GEN-END:variables
}
