/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpr.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author atmik shetty
 */
public class LR extends javax.swing.JFrame {

    /**
     * Creates new form LR
     */
    public LR() {
        initComponents();
    }
    
    public LR(String voter1, String pres1) {
        initComponents();
        pres_1.setText(pres1);
        voter_2.setText(voter1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anushka = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        ritu = new javax.swing.JRadioButton();
        lnext = new javax.swing.JButton();
        voter_2 = new javax.swing.JLabel();
        pres_1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LADY REPRESENTATIVE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 46));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CANDITATE 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 35));

        anushka.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        anushka.setForeground(new java.awt.Color(240, 240, 240));
        anushka.setText("ANUSHKA BHANDARY");
        anushka.setContentAreaFilled(false);
        anushka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anushkaActionPerformed(evt);
            }
        });
        getContentPane().add(anushka, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANDITATE 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 36));

        ritu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ritu.setForeground(new java.awt.Color(240, 240, 240));
        ritu.setText("RITU PAWASKAR");
        ritu.setContentAreaFilled(false);
        ritu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rituActionPerformed(evt);
            }
        });
        getContentPane().add(ritu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 190, 30));

        lnext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lnext.setForeground(new java.awt.Color(255, 255, 255));
        lnext.setText("NEXT");
        lnext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lnext.setContentAreaFilled(false);
        lnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnextActionPerformed(evt);
            }
        });
        getContentPane().add(lnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 123, 69));
        getContentPane().add(voter_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        getContentPane().add(pres_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\atmik shetty\\Pictures\\Screenshots\\background1.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnextActionPerformed
        // TODO add your handling code here:
       
                      
                if(anushka.isSelected()){
                String pres2 = pres_1.getText();
                String lr1 = anushka.getText();
                String voter3 = voter_2.getText();
                new GS(voter3, pres2, lr1).setVisible(true);
                setVisible(false); 
                dispose();
                } 
                
                else if(ritu.isSelected()){
                String pres2 = pres_1.getText();
                String lr1 = ritu.getText();
                String voter3 = voter_2.getText();
                new GS(voter3, pres2, lr1).setVisible(true);
                setVisible(false);    
                dispose();
                } 
                else{
                     JOptionPane.showMessageDialog(null,"select atleast one canditate!!!");
                }
                   
                
    }//GEN-LAST:event_lnextActionPerformed

    private void anushkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anushkaActionPerformed
        // TODO add your handling code here:
        
                if(anushka.isSelected()){
            ritu.setSelected(false);
            
        }
    }//GEN-LAST:event_anushkaActionPerformed

    private void rituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rituActionPerformed
        // TODO add your handling code here:
                if(ritu.isSelected()){
            anushka.setSelected(false);
          
        }
    }//GEN-LAST:event_rituActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anushka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lnext;
    private javax.swing.JLabel pres_1;
    private javax.swing.JRadioButton ritu;
    private javax.swing.JLabel voter_2;
    // End of variables declaration//GEN-END:variables
}
