/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpr.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author atmik shetty
 */
public class President extends javax.swing.JFrame {

    /**
     * Creates new form President
     */
    public President() {
        initComponents();
    }
    
    public President(String voter1){
        initComponents();
        voter_1.setText(voter1);
        voter_1.setVisible(false);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kris = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        nishant = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        aayush = new javax.swing.JRadioButton();
        pnext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        voter_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRESIDENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, 156, 41));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANDITATE 1: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        kris.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        kris.setForeground(new java.awt.Color(255, 255, 255));
        kris.setText("KRIS RAWAL");
        kris.setContentAreaFilled(false);
        kris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                krisActionPerformed(evt);
            }
        });
        getContentPane().add(kris, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANDITATE 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        nishant.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        nishant.setForeground(new java.awt.Color(255, 255, 255));
        nishant.setText("NISHANT GAWDE");
        nishant.setContentAreaFilled(false);
        nishant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nishantActionPerformed(evt);
            }
        });
        getContentPane().add(nishant, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANDITATE 3:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        aayush.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        aayush.setForeground(new java.awt.Color(255, 255, 255));
        aayush.setText("AAYUSH SHENAVI");
        aayush.setContentAreaFilled(false);
        aayush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aayushActionPerformed(evt);
            }
        });
        getContentPane().add(aayush, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        pnext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pnext.setForeground(new java.awt.Color(255, 255, 255));
        pnext.setText("NEXT");
        pnext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnext.setContentAreaFilled(false);
        pnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnextActionPerformed(evt);
            }
        });
        getContentPane().add(pnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 110, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\atmik shetty\\Pictures\\Screenshots\\background1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 590));

        voter_1.setText("jLabel6");
        getContentPane().add(voter_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnextActionPerformed
        // TODO add your handling code here:       
                
                                   
                if(kris.isSelected()){
                String pres1 = kris.getText();
                String voter2 = voter_1.getText();
                new LR(voter2, pres1).setVisible(true);
                setVisible(false);    
                dispose();
                }
                
                
                else if(nishant.isSelected()){
                String pres1 = nishant.getText();
                String voter2 = voter_1.getText();
                new LR(voter2, pres1).setVisible(true);
                setVisible(false);    
                dispose();
                }
                
                else if(aayush.isSelected()){
                String pres1 = aayush.getText();
                String voter2 = voter_1.getText();
                new LR(voter2, pres1).setVisible(true);
                setVisible(false);    
                dispose();
                }
                
                else{
                    JOptionPane.showMessageDialog(null,"select atleast one canditate!!!");
                }
    }//GEN-LAST:event_pnextActionPerformed

    private void krisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_krisActionPerformed
        // TODO add your handling code here:
        
        if(kris.isSelected()){
            nishant.setSelected(false);
            aayush.setSelected(false);
        }
    }//GEN-LAST:event_krisActionPerformed

    private void nishantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nishantActionPerformed
        // TODO add your handling code here:
         
        if(nishant.isSelected()){
            kris.setSelected(false);
            aayush.setSelected(false);
        }
        
    }//GEN-LAST:event_nishantActionPerformed

    private void aayushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aayushActionPerformed
        // TODO add your handling code here:
         kris.setSelected(false);
            nishant.setSelected(false);
        
    }//GEN-LAST:event_aayushActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(President.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(President.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(President.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(President.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new President().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aayush;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton kris;
    private javax.swing.JRadioButton nishant;
    private javax.swing.JButton pnext;
    private javax.swing.JLabel voter_1;
    // End of variables declaration//GEN-END:variables
}
