/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mpr.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author atmik shetty
 */
public class RR extends javax.swing.JFrame {

    /**
     * Creates new form RR
     */
    public RR() {
        initComponents();
    }
    
    public RR(String voter1, String pres1, String lr1, String gs1) {
        initComponents();
        pres_1.setText(pres1);
        voter_4.setText(voter1);
        lr_1.setText(lr1);
        gs_1.setText(gs1);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vikas = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        vedant = new javax.swing.JRadioButton();
        rnext = new javax.swing.JButton();
        pres_1 = new javax.swing.JLabel();
        voter_4 = new javax.swing.JLabel();
        lr_1 = new javax.swing.JLabel();
        gs_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVED REPRESENTATIVE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CANDITATE 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 44));

        vikas.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        vikas.setForeground(new java.awt.Color(255, 255, 255));
        vikas.setText("VIKAS RAI");
        vikas.setContentAreaFilled(false);
        vikas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vikasActionPerformed(evt);
            }
        });
        getContentPane().add(vikas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANDITATE 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 31));

        vedant.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        vedant.setForeground(new java.awt.Color(255, 255, 255));
        vedant.setText("VEDANT SATVI");
        vedant.setContentAreaFilled(false);
        vedant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vedantActionPerformed(evt);
            }
        });
        getContentPane().add(vedant, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        rnext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rnext.setForeground(new java.awt.Color(255, 255, 255));
        rnext.setText("NEXT");
        rnext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rnext.setContentAreaFilled(false);
        rnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnextActionPerformed(evt);
            }
        });
        getContentPane().add(rnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 385, 120, 70));

        pres_1.setIcon(new javax.swing.ImageIcon("C:\\Users\\atmik shetty\\Pictures\\Screenshots\\background1.png")); // NOI18N
        getContentPane().add(pres_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        voter_4.setText("jLabel5");
        getContentPane().add(voter_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        lr_1.setText("jLabel7");
        getContentPane().add(lr_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        gs_1.setText("jLabel7");
        getContentPane().add(gs_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnextActionPerformed
        // TODO add your handling code here:
       
                
                
                 
                if(vikas.isSelected()){
                String pres2 = pres_1.getText();
                String lr1 = lr_1.getText();
                String voter3 = voter_4.getText();
                String gs1 = gs_1.getText();
                String rr1 = vikas.getText();
                new Final(voter3, pres2, lr1, gs1, rr1).setVisible(true);
                setVisible(false);    
                dispose();
                } 
                 
                else if(vedant.isSelected()){
                String pres2 = pres_1.getText();
                String lr1 = lr_1.getText();
                String voter3 = voter_4.getText();
                String gs1 = gs_1.getText();
                String rr1 = vedant.getText();
                new Final(voter3, pres2, lr1, gs1, rr1).setVisible(true);
                setVisible(false);    
                dispose();
                }
                
                 else{
                     JOptionPane.showMessageDialog(null,"select atleast one canditate!!!");
                }
                
                
    }//GEN-LAST:event_rnextActionPerformed

    private void vikasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vikasActionPerformed
        // TODO add your handling code here:
                if(vikas.isSelected()){
            vedant.setSelected(false);
            
        }
    }//GEN-LAST:event_vikasActionPerformed

    private void vedantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vedantActionPerformed
        // TODO add your handling code here:
                if(vedant.isSelected()){
            vikas.setSelected(false);
           
        }
    }//GEN-LAST:event_vedantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gs_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lr_1;
    private javax.swing.JLabel pres_1;
    private javax.swing.JButton rnext;
    private javax.swing.JRadioButton vedant;
    private javax.swing.JRadioButton vikas;
    private javax.swing.JLabel voter_4;
    // End of variables declaration//GEN-END:variables
}
